### ISSUE TITLE
from mask_net import MASK_CLASSIFY

### ISSUE THREAD

**Issue by wolfworld6** [Wulingtian/yolov5_onnx2caffe#1]
hello，thx for your code，but i wanna know where is the mask_net？thx again！

**Comment by Wulingtian** [comment]
Opset version 设置为12试试

**Comment by wolfworld6** [comment]
> Opset version 设置为12试试
您的caffe预测正常吗？有使用过https://github.com/daquexian/onnx-simplifier，去掉shape吗？

**Comment by Wulingtian** [comment]
有使用onnx-simplifier简化过；
部署流程请参考如下文章：
https://zhuanlan.zhihu.com/p/350860351

**Comment by wolfworld6** [comment]
> 有使用onnx-simplifier简化过；
> 部署流程请参考如下文章：
> https://zhuanlan.zhihu.com/p/35086035

能否加您微信请教一些onnx->caffe的问题？谢谢

**Comment by longgang123** [comment]
您好，非常感谢你的code.最近在使用yolov5转onnx 转caffe 现在我从yolov5 官方下了v5s的pt文件然后用export.py 得到onnx 和简化后的sample.onnx 然后用您的converCaffe 运行发现报File "convertCaffe.py", line 159, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
  File "convertCaffe.py", line 83, in convertToCaffe
    layer = converter_fn(node, graph, err)
  File "/kk/LongG/onnx2caffe/onnx2caffe/_operators.py", line 505, in _convert_resize
    height_scale = scales[2]
IndexError: index 2 is out of bounds for axis 0 with size 0
这个应该是upsample里面对W H 进行resize 出问题了对吗 不知道怎么修改；caffe 的upsample是用的message UpsampleParameter {		
	optional int32 height = 1 [default = 32];
	optional int32 width = 2 [default = 32];
	optional int32 height_scale = 3 [default = 2];
	optional int32 width_scale = 4 [default = 2];
	enum UpsampleOp {
		NEAREST = 0;
		BILINEAR = 1;
	}
	optional UpsampleOp mode = 5 [default = BILINEAR];
}

**Comment by Wulingtian** [comment]
> 您好，非常感谢你的code.最近在使用yolov5转onnx 转caffe 现在我从yolov5 官方下了v5s的pt文件然后用export.py 得到onnx 和简化后的sample.onnx 然后用您的converCaffe 运行发现报File "convertCaffe.py", line 159, in
> convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
> File "convertCaffe.py", line 83, in convertToCaffe
> layer = converter_fn(node, graph, err)
> File "/kk/LongG/onnx2caffe/onnx2caffe/_operators.py", line 505, in _convert_resize
> height_scale = scales[2]
> IndexError: index 2 is out of bounds for axis 0 with size 0
> 这个应该是upsample里面对W H 进行resize 出问题了对吗 不知道怎么修改；caffe 的upsample是用的message UpsampleParameter {
> optional int32 height = 1 [default = 32];
> optional int32 width = 2 [default = 32];
> optional int32 height_scale = 3 [default = 2];
> optional int32 width_scale = 4 [default = 2];
> enum UpsampleOp {
> NEAREST = 0;
> BILINEAR = 1;
> }
> optional UpsampleOp mode = 5 [default = BILINEAR];
> }

onnx版本1.8.0 op设置为10

**Comment by longgang123** [comment]
> > 您好，非常感谢你的code.最近在使用yolov5转onnx 转caffe 现在我从yolov5 官方下了v5s的pt文件然后用export.py 得到onnx 和简化后的sample.onnx 然后用您的converCaffe 运行发现报File "convertCaffe.py", line 159, in
> > convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
> > File "convertCaffe.py", line 83, in convertToCaffe
> > layer = converter_fn(node, graph, err)
> > File "/kk/LongG/onnx2caffe/onnx2caffe/_operators.py", line 505, in _convert_resize
> > height_scale = scales[2]
> > IndexError: index 2 is out of bounds for axis 0 with size 0
> > 这个应该是upsample里面对W H 进行resize 出问题了对吗 不知道怎么修改；caffe 的upsample是用的message UpsampleParameter {
> > optional int32 height = 1 [default = 32];
> > optional int32 width = 2 [default = 32];
> > optional int32 height_scale = 3 [default = 2];
> > optional int32 width_scale = 4 [default = 2];
> > enum UpsampleOp {
> > NEAREST = 0;
> > BILINEAR = 1;
> > }
> > optional UpsampleOp mode = 5 [default = BILINEAR];
> > }
> 
> onnx版本1.8.0 op设置为10
我吧onnx 版本和yolov5 export的opt_version 设置为10 生成的onnx 还有您提供的yolov5s-sample.onnx 都conver2Caffe 发生下面的错误 我怀疑是我编译的caffe有问题 
layer_factory.hpp:77] Creating layer Transpose_258
Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Permute (known types: AbsVal, Accuracy, ArgMax, BNLL, BatchNorm, BatchReindex, Bias, Clip, Concat, ContrastiveLoss, Convolution, Crop, Data, Deconvolution, Dropout, DummyData, ELU, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, Input, LRN, LSTM, LSTMUnit, Log, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Parameter, Pooling, Power, Python, RNN, ReLU, Reduction, Reorg, Reshape, SPP, Scale, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, Softmax, SoftmaxWithLoss, Split, Swish, TanH, Threshold, Tile, Upsample, WindowData)
*** Check failure stack trace: ***
Aborted (core dumped) 
但是我的python3.8 是可以成功import caffe 的；
root/LongG/onnx2caffe# python3
Python 3.8.1 (default, Mar  6 2021, 03:36:32)
[GCC 5.4.0 20160609] on linux
>>> import caffe
>>>
还麻烦您指教一下这个问题怎么解决，是否有什么办法可以测试caffe 编译和环境没问题呢 。

**Comment by Cuzny** [comment]
@Wulingtian 

Traceback (most recent call last):
  File "convertCaffe.py", line 159, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41")  
  File "convertCaffe.py", line 97, in convertToCaffe
    layers[id] = layer._to_proto()  # 转为 proto 风格？
  File "E:\yolov5_onnx2caffe-master\MyCaffe.py", line 100, in _to_proto
    assign_proto(layer, k, v)
  File "E:\yolov5_onnx2caffe-master\MyCaffe.py", line 29, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: reorg_param

您好，我的onnx版本和设置和您一样，但是在编译时，出现上述错误，请问您知道是何原因吗？

**Comment by tianxia798898** [comment]
> 您好，非常感谢你的code.最近在使用yolov5转onnx 转caffe 现在我从yolov5 官方下了v5s的pt文件然后用export.py 得到onnx 和简化后的sample.onnx 然后用您的converCaffe 运行发现报File "convertCaffe.py", line 159, in convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41") File "convertCaffe.py", line 83, in convertToCaffe layer = converter_fn(node, graph, err) File "/kk/LongG/onnx2caffe/onnx2caffe/_operators.py", line 505, in _convert_resize height_scale = scales[2] IndexError: index 2 is out of bounds for axis 0 with size 0 这个应该是upsample里面对W H 进行resize 出问题了对吗 不知道怎么修改；caffe 的upsample是用的message UpsampleParameter { optional int32 height = 1 [default = 32]; optional int32 width = 2 [default = 32]; optional int32 height_scale = 3 [default = 2]; optional int32 width_scale = 4 [default = 2]; enum UpsampleOp { NEAREST = 0; BILINEAR = 1; } optional UpsampleOp mode = 5 [default = BILINEAR]; }



> 您好，非常感谢你的code.最近在使用yolov5转onnx 转caffe 现在我从yolov5 官方下了v5s的pt文件然后用export.py 得到onnx 和简化后的sample.onnx 然后用您的converCaffe 运行发现报File "convertCaffe.py", line 159, in convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41") File "convertCaffe.py", line 83, in convertToCaffe layer = converter_fn(node, graph, err) File "/kk/LongG/onnx2caffe/onnx2caffe/_operators.py", line 505, in _convert_resize height_scale = scales[2] IndexError: index 2 is out of bounds for axis 0 with size 0 这个应该是upsample里面对W H 进行resize 出问题了对吗 不知道怎么修改；caffe 的upsample是用的message UpsampleParameter { optional int32 height = 1 [default = 32]; optional int32 width = 2 [default = 32]; optional int32 height_scale = 3 [default = 2]; optional int32 width_scale = 4 [default = 2]; enum UpsampleOp { NEAREST = 0; BILINEAR = 1; } optional UpsampleOp mode = 5 [default = BILINEAR]; }

你好，我也遇到了同样的问题，请问你的问题解决了吗？
