### ISSUE TITLE
yoloV5s onnx to caffemodel

### ISSUE THREAD

**Issue by sunzhongwu** [Wulingtian/yolov5_onnx2caffe#10]

**Comment by sunzhongwu** [comment]
> 我的onnx模型：
> 链接：https://pan.baidu.com/s/1D9shq7URj8dANyEBQZ7RjA
> 提取码：1234
> 
> _**********_convert_conv_slice**********_
> input_name: images
> output_name: 131
> node_name: Slice_4
> input_tensor_keys: ['128', '129', '127']
> axes: [2]
> channels: 3
> starts: [0]
> ends: [9223372036854775807]
> _**********_convert_conv_slice**********_
> input_name: 131
> output_name: 136
> node_name: Slice_9
> input_tensor_keys: ['128', '129', '565', '127']
> axes: [3]
> channels: 3
> starts: [0]
> ends: [9223372036854775807]
> _**********_convert_conv_slice**********_
> input_name: images
> output_name: 141
> node_name: Slice_14
> input_tensor_keys: ['138', '129', '127']
> axes: [2]
> channels: 3
> starts: [1]
> ends: [9223372036854775807]
> _**********_convert_conv_slice**********_
> input_name: 141
> output_name: 146
> node_name: Slice_19
> input_tensor_keys: ['128', '129', '565', '127']
> axes: [3]
> channels: 3
> starts: [0]
> ends: [9223372036854775807]
> _**********_convert_conv_slice**********_
> input_name: images
> output_name: 151
> node_name: Slice_24
> input_tensor_keys: ['128', '129', '127']
> axes: [2]
> channels: 3
> starts: [0]
> ends: [9223372036854775807]
> _**********_convert_conv_slice**********_
> input_name: 151
> output_name: 156
> node_name: Slice_29
> input_tensor_keys: ['138', '129', '565', '127']
> axes: [3]
> channels: 3
> starts: [1]
> ends: [9223372036854775807]
> _**********_convert_conv_slice**********_
> input_name: images
> output_name: 161
> node_name: Slice_34
> input_tensor_keys: ['138', '129', '127']
> axes: [2]
> channels: 3
> starts: [1]
> ends: [9223372036854775807]
> _**********_convert_conv_slice**********_
> input_name: 161
> output_name: 166
> node_name: Slice_39
> input_tensor_keys: ['138', '129', '565', '127']
> axes: [3]
> channels: 3
> starts: [1]
> ends: [9223372036854775807]
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64, '203': 64, '204': 64, '205': 64, '206': 64, '207': 64, '208': 64, '209': 64}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64, '203': 64, '204': 64, '205': 64, '206': 64, '207': 64, '208': 64, '209': 64}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64, '203': 64, '204': 64, '205': 64, '206': 64, '207': 64, '208': 64, '209': 64, '210': 64, '211': 64, '212': 64, '213': 64, '214': 64, '215': 64, '216': 64}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64, '203': 64, '204': 64, '205': 64, '206': 64, '207': 64, '208': 64, '209': 64, '210': 64, '211': 64, '212': 64, '213': 64, '214': 64, '215': 64, '216': 64}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64, '203': 64, '204': 64, '205': 64, '206': 64, '207': 64, '208': 64, '209': 64, '210': 64, '211': 64, '212': 64, '213': 64, '214': 64, '215': 64, '216': 64, '217': 64, '218': 64, '219': 64, '220': 64, '221': 128, '222': 128, '223': 128, '224': 128, '225': 256, '226': 256, '227': 256, '228': 128, '229': 128, '230': 128, '231': 128, '232': 128, '233': 128, '234': 128, '235': 128, '236': 128}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64, '203': 64, '204': 64, '205': 64, '206': 64, '207': 64, '208': 64, '209': 64, '210': 64, '211': 64, '212': 64, '213': 64, '214': 64, '215': 64, '216': 64, '217': 64, '218': 64, '219': 64, '220': 64, '221': 128, '222': 128, '223': 128, '224': 128, '225': 256, '226': 256, '227': 256, '228': 128, '229': 128, '230': 128, '231': 128, '232': 128, '233': 128, '234': 128, '235': 128, '236': 128}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64, '203': 64, '204': 64, '205': 64, '206': 64, '207': 64, '208': 64, '209': 64, '210': 64, '211': 64, '212': 64, '213': 64, '214': 64, '215': 64, '216': 64, '217': 64, '218': 64, '219': 64, '220': 64, '221': 128, '222': 128, '223': 128, '224': 128, '225': 256, '226': 256, '227': 256, '228': 128, '229': 128, '230': 128, '231': 128, '232': 128, '233': 128, '234': 128, '235': 128, '236': 128, '237': 128, '238': 128, '239': 128, '240': 128, '241': 128, '242': 128, '243': 128}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64, '203': 64, '204': 64, '205': 64, '206': 64, '207': 64, '208': 64, '209': 64, '210': 64, '211': 64, '212': 64, '213': 64, '214': 64, '215': 64, '216': 64, '217': 64, '218': 64, '219': 64, '220': 64, '221': 128, '222': 128, '223': 128, '224': 128, '225': 256, '226': 256, '227': 256, '228': 128, '229': 128, '230': 128, '231': 128, '232': 128, '233': 128, '234': 128, '235': 128, '236': 128, '237': 128, '238': 128, '239': 128, '240': 128, '241': 128, '242': 128, '243': 128}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64, '203': 64, '204': 64, '205': 64, '206': 64, '207': 64, '208': 64, '209': 64, '210': 64, '211': 64, '212': 64, '213': 64, '214': 64, '215': 64, '216': 64, '217': 64, '218': 64, '219': 64, '220': 64, '221': 128, '222': 128, '223': 128, '224': 128, '225': 256, '226': 256, '227': 256, '228': 128, '229': 128, '230': 128, '231': 128, '232': 128, '233': 128, '234': 128, '235': 128, '236': 128, '237': 128, '238': 128, '239': 128, '240': 128, '241': 128, '242': 128, '243': 128, '244': 128, '245': 128, '246': 128, '247': 128, '248': 128, '249': 128, '250': 128}
> {'images': 3, '131': 3, '131slice_another': 3, '136': 3, '136slice_another': 3, '141slice_another': 3, '141': 3, '146': 3, '146slice_another': 3, '151': 3, '151slice_another': 3, '156slice_another': 3, '156': 3, '161slice_another': 3, '161': 3, '166slice_another': 3, '166': 3, '167': 12, '168': 32, '169': 32, '170': 32, '171': 64, '172': 64, '173': 64, '174': 32, '175': 32, '176': 32, '177': 32, '178': 32, '179': 32, '180': 32, '181': 32, '182': 32, '183': 32, '184': 32, '185': 32, '186': 32, '187': 64, '188': 64, '189': 64, '190': 64, '191': 128, '192': 128, '193': 128, '194': 64, '195': 64, '196': 64, '197': 64, '198': 64, '199': 64, '200': 64, '201': 64, '202': 64, '203': 64, '204': 64, '205': 64, '206': 64, '207': 64, '208': 64, '209': 64, '210': 64, '211': 64, '212': 64, '213': 64, '214': 64, '215': 64, '216': 64, '217': 64, '218': 64, '219': 64, '220': 64, '221': 128, '222': 128, '223': 128, '224': 128, '225': 256, '226': 256, '227': 256, '228': 128, '229': 128, '230': 128, '231': 128, '232': 128, '233': 128, '234': 128, '235': 128, '236': 128, '237': 128, '238': 128, '239': 128, '240': 128, '241': 128, '242': 128, '243': 128, '244': 128, '245': 128, '246': 128, '247': 128, '248': 128, '249': 128, '250': 128}
> scales = [1. 1. 2. 2.]
> scales = [1. 1. 2. 2.]
> Traceback (most recent call last):
> File "convertCaffe.py", line 160, in
> convertToCaffe(graph, prototxt_path, caffemodel_path)
> File "convertCaffe.py", line 83, in convertToCaffe
> layer = converter_fn(node, graph, err)
> File "/media/omnisky/33d54c8d-3378-433c-961a-3e4c276e175c/Code/darknet/yolov5/yolov5_onnx2caffe/onnx2caffe/_operators.py", line 134, in _convert_sigmoid
> graph.channel_dims[output_name] = graph.channel_dims[input_name]
> KeyError: '395'
