### ISSUE TITLE
AttributeError: upsample_param

### ISSUE THREAD

**Issue by heylary** [Wulingtian/yolov5_onnx2caffe#17]
Anybody encounter this problem?

> Traceback (most recent call last):
>   File "d:\WorkData\DeepLearning\yolov5_onnx2caffe\convertCaffe.py", line 159, in <module>
>     convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=False, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
>   File "d:\WorkData\DeepLearning\yolov5_onnx2caffe\convertCaffe.py", line 97, in convertToCaffe
>     layers[id] = layer._to_proto()  # 转为 proto 风格？
>   File "d:\WorkData\DeepLearning\yolov5_onnx2caffe\MyCaffe.py", line 100, in _to_proto
>     assign_proto(layer, k, v)
>   File "d:\WorkData\DeepLearning\yolov5_onnx2caffe\MyCaffe.py", line 29, in assign_proto
>     is_repeated_field = hasattr(getattr(proto, name), 'extend')
> AttributeError: upsample_param

**Comment by Kittywyk** [comment]
> Anybody encounter this problem?
> 
> > Traceback (most recent call last):
> > File "d:\WorkData\DeepLearning\yolov5_onnx2caffe\convertCaffe.py", line 159, in 
> > convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=False, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
> > File "d:\WorkData\DeepLearning\yolov5_onnx2caffe\convertCaffe.py", line 97, in convertToCaffe
> > layers[id] = layer._to_proto()  # 转为 proto 风格？
> > File "d:\WorkData\DeepLearning\yolov5_onnx2caffe\MyCaffe.py", line 100, in _to_proto
> > assign_proto(layer, k, v)
> > File "d:\WorkData\DeepLearning\yolov5_onnx2caffe\MyCaffe.py", line 29, in assign_proto
> > is_repeated_field = hasattr(getattr(proto, name), 'extend')
> > AttributeError: upsample_param

See this. https://blog.csdn.net/ynzzxc/article/details/116931806
