### ISSUE TITLE
Convert yolov5s.onnx to caffe Failed 

### ISSUE THREAD

**Issue by gtfaiwxm** [Wulingtian/yolov5_onnx2caffe#20]
Hi, I use the tool to convert yolov5s.onnx, failed!
Traceback (most recent call last):
  File "convertCaffe.py", line 159, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
  File "convertCaffe.py", line 83, in convertToCaffe
    layer = converter_fn(node, graph, err)
  File "/data/gtf_project/project/yolov5_onnx2caffe/onnx2caffe/_operators.py", line 505, in _convert_resize
    height_scale = scales[2]
IndexError: index 2 is out of bounds for axis 0 with size 0

**Comment by aiqiangbrave** [comment]
> File "convertCaffe.py", line 159, in

hello，Have you solved the problem ？thanks

**Comment by Lenubolim** [comment]
I have the same problem,who can solve it ? So boring!

**Comment by Waterman0524** [comment]
I have the same problem,who can solve it ? So boring!

**Comment by Lenubolim** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件我已收到。

**Comment by MrQiuriosity** [comment]
I have the same problem
