### ISSUE TITLE
KeyError: '/conv2/conv2.0/gate/fc1/Conv'

### ISSUE THREAD

**Issue by ouxiand** [Wulingtian/yolov5_onnx2caffe#23]
Thank you for open source,there were bugs during use, as detailed below:

I0605 16:19:36.965795 11756 net.cpp:257] Network initialization done.
Traceback (most recent call last):
  File "/home/oo/pycode/yolov5_onnx2caffe/convertCaffe.py", line 162, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
  File "/home/oo/pycode/yolov5_onnx2caffe/convertCaffe.py", line 130, in convertToCaffe
    converter_fn(net, node, graph, err)  # 复制模型参数
  File "/home/oo/pycode/yolov5_onnx2caffe/onnx2caffe/_weightloader.py", line 38, in _convert_conv
    np.copyto(net.params[node_name][0].data, W, casting='same_kind')
KeyError: '/conv2/conv2.0/gate/fc1/Conv'

Can you tell me how to do it?

**Comment by Paulharden1** [comment]
hi,did you solve it?Could you please tell me how to deal with it?thanks!
