### ISSUE TITLE
KeyError: '/model.24/Transpose_output_0'

### ISSUE THREAD

**Issue by 4fris** [Wulingtian/yolov5_onnx2caffe#27]
Traceback (most recent call last):
  File "convertCaffe.py", line 159, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path) 	
  File "convertCaffe.py", line 84, in convertToCaffe
    layer = converter_fn(node, graph, err)
  File "/home/fris/yolov5_onnx2caffe-master/onnx2caffe/_operators.py", line 134, in _convert_sigmoid
    graph.channel_dims[output_name] = graph.channel_dims[input_name]
KeyError: '/model.24/Transpose_output_0'
有dalao能解答下吗谢谢

**Comment by HHgis** [comment]
请问这个解决了嘛

**Comment by SlamDunk-ycw** [comment]
这个解决了嘛 ？ 我也遇到了这个问题

**Comment by BigerPatax** [comment]
还是没解决嘛

**Comment by BigerPatax** [comment]
在yolov5工程里export.py的export_onnx方法，torch.onnx.export方法的参数中加一个training
```python
torch.onnx.export(
        model.cpu() if dynamic else model,  # --dynamic only compatible with cpu
        im.cpu() if dynamic else im,
        f,
        training=torch.onnx.TrainingMode.TRAINING,
        verbose=False,
        opset_version=opset,
        do_constant_folding=True,  # WARNING: DNN inference with torch>=1.12 may require do_constant_folding=False
        input_names=["images"],
        output_names=output_names,
        dynamic_axes=dynamic or None,
    )
```
