### ISSUE TITLE
带focus层的yolov5模型，供大家测试

### ISSUE THREAD

**Issue by Wulingtian** [Wulingtian/yolov5_onnx2caffe#3]
链接: https://pan.baidu.com/s/1Dw45YMYJ3DpnCBR4RngWsw  密码: qtnm

**Comment by duan348733684** [comment]
转你给出的这个模型时，报错

Traceback (most recent call last):
  File "convertCaffe.py", line 160, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
  File "convertCaffe.py", line 98, in convertToCaffe
    layers[id] = layer._to_proto()  # \u8f6c\u4e3a proto \u98ce\u683c\uff1f
  File "/workspace/yolov5_onnx2caffe-master/MyCaffe.py", line 100, in _to_proto
    assign_proto(layer, k, v)
  File "/workspace/yolov5_onnx2caffe-master/MyCaffe.py", line 29, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: reorg_param

**Comment by duan348733684** [comment]
@Wulingtian 
转你给出的这个模型时，报错

Traceback (most recent call last):
File "convertCaffe.py", line 160, in 
convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
File "convertCaffe.py", line 98, in convertToCaffe
layers[id] = layer._to_proto() # \u8f6c\u4e3a proto \u98ce\u683c\uff1f
File "/workspace/yolov5_onnx2caffe-master/MyCaffe.py", line 100, in _to_proto
assign_proto(layer, k, v)
File "/workspace/yolov5_onnx2caffe-master/MyCaffe.py", line 29, in assign_proto
is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: reorg_param

请问这是什么问题，如何解决呢，谢谢

**Comment by duan348733684** [comment]
@Wulingtian

**Comment by sunzhongwu** [comment]
@duan348733684 你是用git clone https://github.com/Wulingtian/yolov5_caffe.git这个caffe吗？focus层是特殊OP单独实现的caffe才能转，我运行没有问题

**Comment by Secondgrade** [comment]
> @Wulingtian
> 转你给出的这个模型时，报错
> 
> Traceback (most recent call last):
> File "convertCaffe.py", line 160, in
> convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
> File "convertCaffe.py", line 98, in convertToCaffe
> layers[id] = layer._to_proto() # \u8f6c\u4e3a proto \u98ce\u683c\uff1f
> File "/workspace/yolov5_onnx2caffe-master/MyCaffe.py", line 100, in _to_proto
> assign_proto(layer, k, v)
> File "/workspace/yolov5_onnx2caffe-master/MyCaffe.py", line 29, in assign_proto
> is_repeated_field = hasattr(getattr(proto, name), 'extend')
> AttributeError: reorg_param
> 
> 请问这是什么问题，如何解决呢，谢谢


你好，请问这个问题你解决了吗

**Comment by sunzhongwu** [comment]
这不yolov5_onnx2caffe这个作者开源的模型哈，需要下载yolov5_caffe实现了focus的特殊版本caffe




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月29日(星期二) 晚上6:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Wulingtian/yolov5_onnx2caffe] 带focus层的yolov5模型，供大家测试 (#3)





  
@Wulingtian
 转你给出的这个模型时，报错
 
Traceback (most recent call last):
 File "convertCaffe.py", line 160, in
 convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
 File "convertCaffe.py", line 98, in convertToCaffe
 layers[id] = layer._to_proto() # \u8f6c\u4e3a proto \u98ce\u683c\uff1f
 File "/workspace/yolov5_onnx2caffe-master/MyCaffe.py", line 100, in _to_proto
 assign_proto(layer, k, v)
 File "/workspace/yolov5_onnx2caffe-master/MyCaffe.py", line 29, in assign_proto
 is_repeated_field = hasattr(getattr(proto, name), 'extend')
 AttributeError: reorg_param
 
请问这是什么问题，如何解决呢，谢谢
  
你好，请问这个问题你解决了吗

**Comment by zmlmanly** [comment]
需要下载作者另外一个项目yolov5_caffe-master，编译成功后可解决reorg层无法识别问题。

**Comment by zmlmanly** [comment]
@Wulingtian 
pt转成caffemodel后，检测结果存在差异，bounding box的x和y差异较大，请问你有遇到过这个问题吗？

**Comment by autolzl** [comment]
@Wulingtian 您好，我按照您的方法把.pt转成onnx，下载https://github.com/ultralytics/yolov5.git，python models/export.py --weights 训练得到的模型权重路径 --img-size 训练图片输入尺寸（onnx=1.8.0,opset =10），python -m onnxsim onnx模型名称 yolov5s-simple.onnx 得到最终简化后的onnx模型。转完onnx之后和这个样例对比，发现网络不一样，导致后边onnx转换caffe model报错，但是用这个样例转caffe model 没有问题，这是什么原因？，急急急
