### ISSUE TITLE
error when convert .pt to .caffemodel

### ISSUE THREAD

**Issue by Taotaoxu** [Wulingtian/yolov5_onnx2caffe#5]
Hi, 
I follow the [article](https://mp.weixin.qq.com/s/IYwjUpV4iYBbqIsTcwgYlg) to convert yolov5s.pt to yolov5.caffemodel, but I encountered some issues. 

1. The same problem as [issue #4](https://github.com/Wulingtian/yolov5_onnx2caffe/issues/4). So, I change the **onnx** to **onnx==1.8.0**, and the parameter of  [opset_version](https://github.com/ultralytics/yolov5/blob/ed2c74218d6d46605cc5fa68ce9bd6ece213abe4/models/export.py#L77) to **10**. The problem  [issue #4](https://github.com/Wulingtian/yolov5_onnx2caffe/issues/4) is gone.
2. But the error becomes as follow:

```
Traceback (most recent call last):
  File "convertCaffe.py", line 160, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path, exis_focus=True, focus_concat_name="Concat_40", focus_conv_name="Conv_41")
  File "convertCaffe.py", line 98, in convertToCaffe
    layers[id] = layer._to_proto()  # \u8f6c\u4e3a proto \u98ce\u683c\uff1f
  File "/workspace/yolov5_onnx2caffe-master/MyCaffe.py", line 100, in _to_proto
    assign_proto(layer, k, v)
  File "/workspace/yolov5_onnx2caffe-master/MyCaffe.py", line 29, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: reorg_param

```

Could you please provide any suggestions?

**Comment by 1326243249** [comment]
I have the same question. Do you know how to solve it now?

**Comment by duan348733684** [comment]
@Taotaoxu Hi, did you solve this problem?

**Comment by practiceC** [comment]
Does anyone solve this problem?

**Comment by duan348733684** [comment]
@practiceC  @Taotaoxu  @1326243249  did you solve this problem?

**Comment by practiceC** [comment]
@duan348733684 作者使用的caffe不是官网的版本。https://github.com/Wulingtian/yolov5_caffe，作者仓库里面caffe是包含reorg、permute等layer的，因此将caffe更换为作者相同的版本即可。

**Comment by Cuzny** [comment]
想请问一下这个能在虚拟机上跑吗
